name: shramikBackend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Copy code to server directory
        run: |
          sudo mkdir -p /var/www/shramikBackend
          sudo rsync -av --delete ./ /var/www/shramikBackend/
          sudo chown -R ubuntu:ubuntu /var/www/shramikBackend

      - name: Create env file
        run: |
          echo "${{ secrets.BACKENDENV }}" > /var/www/shramikBackend/.env

      - name: Restart backend with PM2
        run: |
          cd /var/www/shramikBackend
          pm2 start server.js --name shramikBackend || pm2 restart shramikBackend
          pm2 save
 
